name: Manual workflow

on: workflow_dispatch

env:
  SOLUTION_FILE_PATH: ColorControl.sln
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: ${{env.BUILD_PLATFORM}}

    - working-directory: "${{github.workspace}}"
      run: nuget restore "${{env.SOLUTION_FILE_PATH}}"

    - working-directory: "${{github.workspace}}"
      shell: cmd
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: |
        MSBuild -m -p:Configuration="${{env.BUILD_CONFIGURATION}}" -p:Platform=${{env.BUILD_PLATFORM}} "${{env.SOLUTION_FILE_PATH}}"

    - uses: actions/upload-artifact@v4
      with:
        path: "${{github.workspace}}"
